apiVersion: apps/v1
kind: Deployment
metadata:
  name: gcp-devops-gke
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: gcp
  template: 
    metadata: 
      labels:
        app: gcp
    specs:
      containers:
      - name: gcp-devops-gke
        image: gcr.io/kodekloud-gcp-training/test-gcpdevops:latest
        ports:
        - ContainerPort: 5000
        env: 
          - name: PORT
            value: "5000" 
apiVersion: "v1"
kind: "Service"
metadata:
  name: "gke-devops-gke-service"
  namespace: "default"
  labels:
    app.kubernetes.io/managed-by: "gcp-cloud-build-deploy"
spec:
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 5000
  selector:
    app: "gcp"
  type: "LoadBalancer"